services:
  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: inventory_app
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "3307:3306"

  app:
    build:
      context: .
    image: inventory_app
    container_name: inventory_app
    depends_on:
      - db
    env_file:
      - .env-docker
    ports:
      - "8081:8080"