services:
  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: inventory_app
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${MYSQL_PORT_HOST}:${MYSQL_PORT_CONTAINER}"

  redis:
    image: redis:7
    container_name: redis_server
    restart: always
    ports:
      - "${REDIS_PORT_HOST}:${REDIS_PORT_CONTAINER}"

  app:
    build:
      context: .
    image: inventory_app
    container_name: inventory_app
    depends_on:
      - db
      - redis
    env_file:
      - .env-docker
    ports:
      - "${APP_PORT_HOST}:${APP_PORT_CONTAINER}"